name: Listacular
options:
  bundleIdPrefix: com.taco23
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true
settings:
  base:
    DEVELOPMENT_TEAM: LTU7433MF2
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "6.0"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
packages:
  SwiftyDropbox:
    url: https://github.com/dropbox/SwiftyDropbox.git
    from: "10.0.0"
targets:
  Listacular:
    type: application
    platform: iOS
    sources:
      - path: Listacular
    dependencies:
      - package: SwiftyDropbox
        product: SwiftyDropbox
    settings:
      base:
        INFOPLIST_FILE: Listacular/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.taco23.listacular
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_STRICT_CONCURRENCY: complete
    info:
      path: Listacular/Info.plist
      properties:
        CFBundleName: Listacular
        CFBundleDisplayName: Listacular
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        CFBundleIconName: AppIcon
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        ITSAppUsesNonExemptEncryption: false
        CFBundleURLTypes:
          - CFBundleURLSchemes:
              - "db-DROPBOX_APP_KEY"
            CFBundleURLName: "Dropbox"
          - CFBundleURLSchemes:
              - "listacular"
            CFBundleURLName: "Listacular"
